import { StyleSheet } from 'react-native';
import { COLORS } from './colors';

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  container: {
    flex: 1,
    backgroundColor: COLORS.bg,
  },
  content: {
    padding: 20,
    paddingBottom: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  greeting: {
    fontSize: 24,
    fontWeight: '800',
    color: COLORS.textMain,
  },
  storeName: {
    fontSize: 13,
    color: COLORS.textSub,
    marginTop: 2,
  },
  bellBtn: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: COLORS.card,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  bellIcon: {
    fontSize: 18,
  },
  totalCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    shadowColor: '#00C97A',
    shadowOpacity: 0.10,
    shadowRadius: 12,
    elevation: 3,
  },
  totalLabel: {
    fontSize: 14,
    color: COLORS.textSub,
    fontWeight: '600',
    marginBottom: 4,
  },
  totalAmount: {
    fontSize: 30,
    fontWeight: '900',
    color: COLORS.primary,
    letterSpacing: -0.5,
  },
  totalSub: {
    fontSize: 12,
    color: COLORS.textSub,
    marginTop: 4,
  },
  totalIcon: {
    width: 60,
    height: 60,
    borderRadius: 16,
    backgroundColor: COLORS.bg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statsRow: {
    flexDirection: 'row',
    marginBottom: 22,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.card,
    borderRadius: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.textSub,
    fontWeight: '600',
    marginBottom: 6,
  },
  statAmount: {
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 8,
  },
  statBadge: {
    alignSelf: 'flex-start',
    borderRadius: 20,
    paddingHorizontal: 10,
    paddingVertical: 3,
  },
  statBadgeText: {
    fontSize: 11,
    fontWeight: '700',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '800',
    color: COLORS.textMain,
    marginBottom: 12,
  },
  activityCard: {
    backgroundColor: COLORS.card,
    borderRadius: 20,
    padding: 8,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 10,
  },
  activityDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#F0F4F0',
  },
  avatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  avatarText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 14,
  },
  activityInfo: {
    flex: 1,
  },
  activityName: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.textMain,
  },
  activitySub: {
    fontSize: 12,
    color: COLORS.textSub,
    marginTop: 2,
  },
  activityAmount: {
    fontSize: 14,
    fontWeight: '800',
  },
  btnRow: {
    flexDirection: 'row',
    gap: 12,
  },
  btnOutline: {
    flex: 1,
    borderWidth: 2,
    borderColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
    backgroundColor: COLORS.card,
  },
  btnOutlineText: {
    color: COLORS.primary,
    fontWeight: '800',
    fontSize: 14,
  },
  btnFill: {
    flex: 1,
    backgroundColor: COLORS.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: 'center',
  },
  btnFillText: {
    color: '#FFF',
    fontWeight: '800',
    fontSize: 14,
  },
});