import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';
export const pagosStyles = StyleSheet.create({
safe: {
    flex: 1,
    backgroundColor: COLORS.primary,
},
header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 4,
},
headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.white,
},
bellBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255,255,255,0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.white,
},
subHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingBottom: 16,
    gap: 6,
},
subHeaderText: {
    color: COLORS.white,
    fontSize: 13,
    fontWeight: '500',
},
card: {
    flex: 1,
    backgroundColor: COLORS.bg,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    paddingHorizontal: 20,
    paddingTop: 24,
    paddingBottom: 24,
},
searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 50,
    marginBottom: 16,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: COLORS.border,
},
searchInput: {
    flex: 1,
    paddingHorizontal: 20,
    paddingVertical: 13,
    fontSize: 14,
    color: COLORS.text,
},
searchBtn: {
    backgroundColor: COLORS.text,
    paddingHorizontal: 18,
    paddingVertical: 13,
    justifyContent: 'center',
    alignItems: 'center',
},
filtersRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
},
filterBtn: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 50,
    borderWidth: 1.5,
    borderColor: COLORS.border,
    backgroundColor: COLORS.white,
},
filterBtnActive: {
    backgroundColor: COLORS.primary,
    borderColor: COLORS.primary,
},
filterText: {
    fontSize: 12,
    color: COLORS.text,
    fontWeight: '500',
},
filterTextActive: {
    color: COLORS.white,
},
listContent: {
    paddingBottom: 16,
},
pagoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
},
pagoIconWrap: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.abonoBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
},
pagoIconText: {
    fontSize: 18,
    fontWeight: '800',
    color: COLORS.abonoIcon,
},
pagoInfo: {
    flex: 1,
    marginRight: 8,
},
pagoNombre: {
    fontSize: 14,
    fontWeight: '700',
    color: COLORS.text,
    marginBottom: 3,
},
pagoSub: {
    fontSize: 12,
    color: COLORS.textMuted,
},
pagoMontoCol: {
    alignItems: 'flex-end',
},
pagoMonto: {
    fontSize: 14,
    fontWeight: '800',
    color: COLORS.primary,
    marginBottom: 4,
},
pagoFecha: {
    fontSize: 11,
    color: COLORS.textMuted,
},
btnRegistrar: {
    backgroundColor: COLORS.primary,
    borderRadius: 50,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
},
btnRegistrarText: {
    color: COLORS.white,
    fontSize: 15,
    fontWeight: '700',
},
emptyText: {
    textAlign: 'center',
    color: COLORS.textMuted,
    marginTop: 40,
    fontSize: 14,
},
});
