name: Deploy ML to Azure

on:
  push:
    branches: [develop]
    paths:
      - 'backend/ml_service/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        working-directory: backend/ml_service
        run: pip install -r requirements.txt --target=".python_packages/lib/site-packages"

      - name: Deploy a Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: fiadocheck-ml
          publish-profile: ${{ secrets.AZURE_ML_PUBLISH_PROFILE }}
          package: backend/ml_service